### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by emmalait** [kohdataan/kohdataan-backend#108]
**Description**
When user registers, they are sent an email with a link for email verification. When user clicks the link, the email is verified and they are redirected to login screen. See: https://zpl.io/ad1mR6l

If user tries to log in without having verified their email address, login should fail and they should be shown an error.

After this has been implemented, make another task for frontend changes needed.
--------------------------------------------------
About the implementation:
- [x] create a column emailVerified to the user table 
- [x] create a separate table for the user-uuid values
- [x] create a controller that creates an entry to the table with use -uuid values

**Comment by KaroliinaM** [comment]
About the implementation:
[] add a emailverefiel field to the database table user
[] add a separate table usedr-uuid
[] add a controller that gets the user email, and creates a table entry with the user

**Comment by KaroliinaM** [comment]
![verify_email](https://user-images.githubusercontent.com/22050953/70323560-bce9e580-1835-11ea-8355-9792de55e8c1.png)
Tein kaavion kokonaisuudesta
