### ISSUE TITLE
User model

### ISSUE THREAD

**Issue by synyker** [kohdataan/kohdataan-backend#17]
**Describe the feature**
A user model that acts as a profile, can be linked to interests & questions and a mattermost account.

**Describe the solution you'd like**
Use Passport and Sequelize to do something like this: https://dev.to/gm456742/building-a-nodejs-web-app-using-passportjs-for-authentication-3ge2 except with PostgreSQL

User fields:
* email
* username/nickname
* description
* is_admin

**Comment by jannetim** [comment]
Done otherwise but questions and their implementation are still pending
