### ISSUE TITLE
Create initial routes for NodeJS backend

### ISSUE THREAD

**Issue by synyker** [kohdataan/kohdataan-backend#37]
**Describe the feature**
Create the following initial routes.

* User
  * Create, Read, Update, Delete
* Interest
  * Create, Read, Update, Delete
* Question
  * Create, Read, Update, Delete
* UserInterest
  * Create, Read, Update, Delete
* UserQuestion
  * Create, Read, Update, Delete
* ChannelInvitation
  * Create, Read, Update, Delete
* SendImageToChannel
* SendAudioToChannel
* LeaveChannel

**Describe the solution you'd like**
The routes should all exist, pending implementation. They should all respond with 501 Not Yet Implemented.

**Describe alternatives you've considered**
You can additionally create skeletons of the models, too.

**Additional context**
-

**Comment by Pninja** [comment]
@all-contributors please add @petrutsi for infra and code
