### ISSUE TITLE
Delete user flow

### ISSUE THREAD

**Issue by synyker** [kohdataan/kohdataan-backend#40]
**Describe the feature**
Deleting the user's profile, messages and all related data.

**Describe the solution you'd like**
Still needs to be refined:
* Do we just delete all the messages sent by the user and leave holes in the discussions they participated in?
* Do we change their messages to say <message deleted> and hide their name?
* Should something else be considered?

**Additional context**

**Comment by samip5** [comment]
It could be done like how Discord does, the username changes to "Deleted User" and the messages are retained.
